# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .colo_argo_analytics_for_geolocation_argo_analytics_for_a_zone_at_different_po_ps_response import (
    ColoArgoAnalyticsForGeolocationArgoAnalyticsForAZoneAtDifferentPoPsResponse as ColoArgoAnalyticsForGeolocationArgoAnalyticsForAZoneAtDifferentPoPsResponse,
)
