# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .nel_edit_params import NELEditParams as NELEditParams
from .ssl_edit_params import SSLEditParams as SSLEditParams
from .waf_edit_params import WAFEditParams as WAFEditParams
from .ipv6_edit_params import IPV6EditParams as IPV6EditParams
from .nel_get_response import NELGetResponse as NELGetResponse
from .ssl_get_response import SSLGetResponse as SSLGetResponse
from .waf_get_response import WAFGetResponse as WAFGetResponse
from .webp_edit_params import WebpEditParams as WebpEditParams
from .http2_edit_params import HTTP2EditParams as HTTP2EditParams
from .http3_edit_params import HTTP3EditParams as HTTP3EditParams
from .ipv6_get_response import IPV6GetResponse as IPV6GetResponse
from .nel_edit_response import NELEditResponse as NELEditResponse
from .ssl_edit_response import SSLEditResponse as SSLEditResponse
from .waf_edit_response import WAFEditResponse as WAFEditResponse
from .webp_get_response import WebpGetResponse as WebpGetResponse
from .brotli_edit_params import BrotliEditParams as BrotliEditParams
from .cipher_edit_params import CipherEditParams as CipherEditParams
from .http2_get_response import HTTP2GetResponse as HTTP2GetResponse
from .http3_get_response import HTTP3GetResponse as HTTP3GetResponse
from .ipv6_edit_response import IPV6EditResponse as IPV6EditResponse
from .minify_edit_params import MinifyEditParams as MinifyEditParams
from .mirage_edit_params import MirageEditParams as MirageEditParams
from .polish_edit_params import PolishEditParams as PolishEditParams
from .webp_edit_response import WebpEditResponse as WebpEditResponse
from .brotli_get_response import BrotliGetResponse as BrotliGetResponse
from .cipher_get_response import CipherGetResponse as CipherGetResponse
from .http2_edit_response import HTTP2EditResponse as HTTP2EditResponse
from .http3_edit_response import HTTP3EditResponse as HTTP3EditResponse
from .minify_get_response import MinifyGetResponse as MinifyGetResponse
from .mirage_get_response import MirageGetResponse as MirageGetResponse
from .polish_get_response import PolishGetResponse as PolishGetResponse
from .tls_1_3_edit_params import TLS1_3EditParams as TLS1_3EditParams
from .brotli_edit_response import BrotliEditResponse as BrotliEditResponse
from .cipher_edit_response import CipherEditResponse as CipherEditResponse
from .minify_edit_response import MinifyEditResponse as MinifyEditResponse
from .mirage_edit_response import MirageEditResponse as MirageEditResponse
from .polish_edit_response import PolishEditResponse as PolishEditResponse
from .tls_1_3_get_response import TLS1_3GetResponse as TLS1_3GetResponse
from .zero_rtt_edit_params import ZeroRTTEditParams as ZeroRTTEditParams
from .tls_1_3_edit_response import TLS1_3EditResponse as TLS1_3EditResponse
from .websocket_edit_params import WebsocketEditParams as WebsocketEditParams
from .zero_rtt_get_response import ZeroRTTGetResponse as ZeroRTTGetResponse
from .early_hint_edit_params import EarlyHintEditParams as EarlyHintEditParams
from .websocket_get_response import WebsocketGetResponse as WebsocketGetResponse
from .zero_rtt_edit_response import ZeroRTTEditResponse as ZeroRTTEditResponse
from .cache_level_edit_params import CacheLevelEditParams as CacheLevelEditParams
from .early_hint_get_response import EarlyHintGetResponse as EarlyHintGetResponse
from .pseudo_ipv4_edit_params import PseudoIPV4EditParams as PseudoIPV4EditParams
from .websocket_edit_response import WebsocketEditResponse as WebsocketEditResponse
from .cache_level_get_response import CacheLevelGetResponse as CacheLevelGetResponse
from .early_hint_edit_response import EarlyHintEditResponse as EarlyHintEditResponse
from .font_setting_edit_params import FontSettingEditParams as FontSettingEditParams
from .pseudo_ipv4_get_response import PseudoIPV4GetResponse as PseudoIPV4GetResponse
from .always_online_edit_params import AlwaysOnlineEditParams as AlwaysOnlineEditParams
from .browser_check_edit_params import BrowserCheckEditParams as BrowserCheckEditParams
from .cache_level_edit_response import CacheLevelEditResponse as CacheLevelEditResponse
from .challenge_ttl_edit_params import ChallengeTTLEditParams as ChallengeTTLEditParams
from .font_setting_get_response import FontSettingGetResponse as FontSettingGetResponse
from .pseudo_ipv4_edit_response import PseudoIPV4EditResponse as PseudoIPV4EditResponse
from .rocket_loader_edit_params import RocketLoaderEditParams as RocketLoaderEditParams
from .advanced_ddos_get_response import AdvancedDDOSGetResponse as AdvancedDDOSGetResponse
from .always_online_get_response import AlwaysOnlineGetResponse as AlwaysOnlineGetResponse
from .browser_check_get_response import BrowserCheckGetResponse as BrowserCheckGetResponse
from .challenge_ttl_get_response import ChallengeTTLGetResponse as ChallengeTTLGetResponse
from .font_setting_edit_response import FontSettingEditResponse as FontSettingEditResponse
from .image_resizing_edit_params import ImageResizingEditParams as ImageResizingEditParams
from .ip_geolocation_edit_params import IPGeolocationEditParams as IPGeolocationEditParams
from .rocket_loader_get_response import RocketLoaderGetResponse as RocketLoaderGetResponse
from .security_level_edit_params import SecurityLevelEditParams as SecurityLevelEditParams
from .always_online_edit_response import AlwaysOnlineEditResponse as AlwaysOnlineEditResponse
from .browser_check_edit_response import BrowserCheckEditResponse as BrowserCheckEditResponse
from .challenge_ttl_edit_response import ChallengeTTLEditResponse as ChallengeTTLEditResponse
from .image_resizing_get_response import ImageResizingGetResponse as ImageResizingGetResponse
from .ip_geolocation_get_response import IPGeolocationGetResponse as IPGeolocationGetResponse
from .min_tls_version_edit_params import MinTLSVersionEditParams as MinTLSVersionEditParams
from .mobile_redirect_edit_params import MobileRedirectEditParams as MobileRedirectEditParams
from .rocket_loader_edit_response import RocketLoaderEditResponse as RocketLoaderEditResponse
from .security_header_edit_params import SecurityHeaderEditParams as SecurityHeaderEditParams
from .security_level_get_response import SecurityLevelGetResponse as SecurityLevelGetResponse
from .ssl_recommender_edit_params import SSLRecommenderEditParams as SSLRecommenderEditParams
from .tls_client_auth_edit_params import TLSClientAuthEditParams as TLSClientAuthEditParams
from .always_use_https_edit_params import AlwaysUseHTTPSEditParams as AlwaysUseHTTPSEditParams
from .development_mode_edit_params import DevelopmentModeEditParams as DevelopmentModeEditParams
from .image_resizing_edit_response import ImageResizingEditResponse as ImageResizingEditResponse
from .ip_geolocation_edit_response import IPGeolocationEditResponse as IPGeolocationEditResponse
from .min_tls_version_get_response import MinTLSVersionGetResponse as MinTLSVersionGetResponse
from .mobile_redirect_get_response import MobileRedirectGetResponse as MobileRedirectGetResponse
from .orange_to_orange_edit_params import OrangeToOrangeEditParams as OrangeToOrangeEditParams
from .prefetch_preload_edit_params import PrefetchPreloadEditParams as PrefetchPreloadEditParams
from .security_header_get_response import SecurityHeaderGetResponse as SecurityHeaderGetResponse
from .security_level_edit_response import SecurityLevelEditResponse as SecurityLevelEditResponse
from .ssl_recommender_get_response import SSLRecommenderGetResponse as SSLRecommenderGetResponse
from .tls_client_auth_get_response import TLSClientAuthGetResponse as TLSClientAuthGetResponse
from .always_use_https_get_response import AlwaysUseHTTPSGetResponse as AlwaysUseHTTPSGetResponse
from .browser_cache_ttl_edit_params import BrowserCacheTTLEditParams as BrowserCacheTTLEditParams
from .development_mode_get_response import DevelopmentModeGetResponse as DevelopmentModeGetResponse
from .email_obfuscation_edit_params import EmailObfuscationEditParams as EmailObfuscationEditParams
from .h2_prioritization_edit_params import H2PrioritizationEditParams as H2PrioritizationEditParams
from .min_tls_version_edit_response import MinTLSVersionEditResponse as MinTLSVersionEditResponse
from .mobile_redirect_edit_response import MobileRedirectEditResponse as MobileRedirectEditResponse
from .orange_to_orange_get_response import OrangeToOrangeGetResponse as OrangeToOrangeGetResponse
from .prefetch_preload_get_response import PrefetchPreloadGetResponse as PrefetchPreloadGetResponse
from .security_header_edit_response import SecurityHeaderEditResponse as SecurityHeaderEditResponse
from .ssl_recommender_edit_response import SSLRecommenderEditResponse as SSLRecommenderEditResponse
from .tls_client_auth_edit_response import TLSClientAuthEditResponse as TLSClientAuthEditResponse
from .always_use_https_edit_response import AlwaysUseHTTPSEditResponse as AlwaysUseHTTPSEditResponse
from .browser_cache_ttl_get_response import BrowserCacheTTLGetResponse as BrowserCacheTTLGetResponse
from .development_mode_edit_response import DevelopmentModeEditResponse as DevelopmentModeEditResponse
from .email_obfuscation_get_response import EmailObfuscationGetResponse as EmailObfuscationGetResponse
from .h2_prioritization_get_response import H2PrioritizationGetResponse as H2PrioritizationGetResponse
from .hotlink_protection_edit_params import HotlinkProtectionEditParams as HotlinkProtectionEditParams
from .orange_to_orange_edit_response import OrangeToOrangeEditResponse as OrangeToOrangeEditResponse
from .prefetch_preload_edit_response import PrefetchPreloadEditResponse as PrefetchPreloadEditResponse
from .proxy_read_timeout_edit_params import ProxyReadTimeoutEditParams as ProxyReadTimeoutEditParams
from .response_buffering_edit_params import ResponseBufferingEditParams as ResponseBufferingEditParams
from .browser_cache_ttl_edit_response import BrowserCacheTTLEditResponse as BrowserCacheTTLEditResponse
from .email_obfuscation_edit_response import EmailObfuscationEditResponse as EmailObfuscationEditResponse
from .h2_prioritization_edit_response import H2PrioritizationEditResponse as H2PrioritizationEditResponse
from .hotlink_protection_get_response import HotlinkProtectionGetResponse as HotlinkProtectionGetResponse
from .opportunistic_onion_edit_params import OpportunisticOnionEditParams as OpportunisticOnionEditParams
from .proxy_read_timeout_get_response import ProxyReadTimeoutGetResponse as ProxyReadTimeoutGetResponse
from .response_buffering_get_response import ResponseBufferingGetResponse as ResponseBufferingGetResponse
from .server_side_exclude_edit_params import ServerSideExcludeEditParams as ServerSideExcludeEditParams
from .hotlink_protection_edit_response import HotlinkProtectionEditResponse as HotlinkProtectionEditResponse
from .opportunistic_onion_get_response import OpportunisticOnionGetResponse as OpportunisticOnionGetResponse
from .proxy_read_timeout_edit_response import ProxyReadTimeoutEditResponse as ProxyReadTimeoutEditResponse
from .response_buffering_edit_response import ResponseBufferingEditResponse as ResponseBufferingEditResponse
from .server_side_exclude_get_response import ServerSideExcludeGetResponse as ServerSideExcludeGetResponse
from .opportunistic_onion_edit_response import OpportunisticOnionEditResponse as OpportunisticOnionEditResponse
from .server_side_exclude_edit_response import ServerSideExcludeEditResponse as ServerSideExcludeEditResponse
from .true_client_ip_header_edit_params import TrueClientIPHeaderEditParams as TrueClientIPHeaderEditParams
from .true_client_ip_header_get_response import TrueClientIPHeaderGetResponse as TrueClientIPHeaderGetResponse
from .automatic_https_rewrite_edit_params import AutomaticHTTPSRewriteEditParams as AutomaticHTTPSRewriteEditParams
from .origin_max_http_version_edit_params import OriginMaxHTTPVersionEditParams as OriginMaxHTTPVersionEditParams
from .true_client_ip_header_edit_response import TrueClientIPHeaderEditResponse as TrueClientIPHeaderEditResponse
from .automatic_https_rewrite_get_response import AutomaticHTTPSRewriteGetResponse as AutomaticHTTPSRewriteGetResponse
from .opportunistic_encryption_edit_params import OpportunisticEncryptionEditParams as OpportunisticEncryptionEditParams
from .origin_max_http_version_get_response import OriginMaxHTTPVersionGetResponse as OriginMaxHTTPVersionGetResponse
from .automatic_https_rewrite_edit_response import (
    AutomaticHTTPSRewriteEditResponse as AutomaticHTTPSRewriteEditResponse,
)
from .opportunistic_encryption_get_response import (
    OpportunisticEncryptionGetResponse as OpportunisticEncryptionGetResponse,
)
from .origin_max_http_version_edit_response import OriginMaxHTTPVersionEditResponse as OriginMaxHTTPVersionEditResponse
from .opportunistic_encryption_edit_response import (
    OpportunisticEncryptionEditResponse as OpportunisticEncryptionEditResponse,
)
from .origin_error_page_pass_thru_edit_params import (
    OriginErrorPagePassThruEditParams as OriginErrorPagePassThruEditParams,
)
from .sort_query_string_for_cache_edit_params import (
    SortQueryStringForCacheEditParams as SortQueryStringForCacheEditParams,
)
from .origin_error_page_pass_thru_get_response import (
    OriginErrorPagePassThruGetResponse as OriginErrorPagePassThruGetResponse,
)
from .sort_query_string_for_cache_get_response import (
    SortQueryStringForCacheGetResponse as SortQueryStringForCacheGetResponse,
)
from .origin_error_page_pass_thru_edit_response import (
    OriginErrorPagePassThruEditResponse as OriginErrorPagePassThruEditResponse,
)
from .sort_query_string_for_cache_edit_response import (
    SortQueryStringForCacheEditResponse as SortQueryStringForCacheEditResponse,
)
from .automatic_platform_optimization_edit_params import (
    AutomaticPlatformOptimizationEditParams as AutomaticPlatformOptimizationEditParams,
)
from .automatic_platform_optimization_get_response import (
    AutomaticPlatformOptimizationGetResponse as AutomaticPlatformOptimizationGetResponse,
)
from .automatic_platform_optimization_edit_response import (
    AutomaticPlatformOptimizationEditResponse as AutomaticPlatformOptimizationEditResponse,
)
