# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .url_info_phishing_url_information_get_results_for_a_url_scan_params import (
    URLInfoPhishingURLInformationGetResultsForAURLScanParams as URLInfoPhishingURLInformationGetResultsForAURLScanParams,
)
from .submit_phishing_url_scanner_submit_suspicious_url_for_scanning_params import (
    SubmitPhishingURLScannerSubmitSuspiciousURLForScanningParams as SubmitPhishingURLScannerSubmitSuspiciousURLForScanningParams,
)
from .url_info_phishing_url_information_get_results_for_a_url_scan_response import (
    URLInfoPhishingURLInformationGetResultsForAURLScanResponse as URLInfoPhishingURLInformationGetResultsForAURLScanResponse,
)
from .submit_phishing_url_scanner_submit_suspicious_url_for_scanning_response import (
    SubmitPhishingURLScannerSubmitSuspiciousURLForScanningResponse as SubmitPhishingURLScannerSubmitSuspiciousURLForScanningResponse,
)
