# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .widget_list_params import WidgetListParams as WidgetListParams
from .widget_get_response import WidgetGetResponse as WidgetGetResponse
from .widget_create_params import WidgetCreateParams as WidgetCreateParams
from .widget_list_response import WidgetListResponse as WidgetListResponse
from .widget_update_params import WidgetUpdateParams as WidgetUpdateParams
from .widget_create_response import WidgetCreateResponse as WidgetCreateResponse
from .widget_delete_response import WidgetDeleteResponse as WidgetDeleteResponse
from .widget_update_response import WidgetUpdateResponse as WidgetUpdateResponse
from .widget_rotate_secret_params import WidgetRotateSecretParams as WidgetRotateSecretParams
from .widget_rotate_secret_response import WidgetRotateSecretResponse as WidgetRotateSecretResponse
