# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .setting_available_page_rules_settings_list_available_page_rules_settings_response import (
    SettingAvailablePageRulesSettingsListAvailablePageRulesSettingsResponse as SettingAvailablePageRulesSettingsListAvailablePageRulesSettingsResponse,
)
