# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .status_ip_address_management_dynamic_advertisement_get_advertisement_status_response import (
    StatusIPAddressManagementDynamicAdvertisementGetAdvertisementStatusResponse as StatusIPAddressManagementDynamicAdvertisementGetAdvertisementStatusResponse,
)
from .status_ip_address_management_dynamic_advertisement_update_prefix_dynamic_advertisement_status_response import (
    StatusIPAddressManagementDynamicAdvertisementUpdatePrefixDynamicAdvertisementStatusResponse as StatusIPAddressManagementDynamicAdvertisementUpdatePrefixDynamicAdvertisementStatusResponse,
)
from .status_ip_address_management_dynamic_advertisement_update_prefix_dynamic_advertisement_status_params import (
    StatusIPAddressManagementDynamicAdvertisementUpdatePrefixDynamicAdvertisementStatusParams as StatusIPAddressManagementDynamicAdvertisementUpdatePrefixDynamicAdvertisementStatusParams,
)
