# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .full_magic_network_monitoring_configuration_list_rules_and_account_configuration_response import (
    FullMagicNetworkMonitoringConfigurationListRulesAndAccountConfigurationResponse as FullMagicNetworkMonitoringConfigurationListRulesAndAccountConfigurationResponse,
)
