# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .fallback_origin_get_response import FallbackOriginGetResponse as FallbackOriginGetResponse
from .fallback_origin_update_params import FallbackOriginUpdateParams as FallbackOriginUpdateParams
from .fallback_origin_delete_response import FallbackOriginDeleteResponse as FallbackOriginDeleteResponse
from .fallback_origin_update_response import FallbackOriginUpdateResponse as FallbackOriginUpdateResponse
