# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .ownership_magic_pcap_collection_add_buckets_for_full_packet_captures_response import (
    OwnershipMagicPcapCollectionAddBucketsForFullPacketCapturesResponse as OwnershipMagicPcapCollectionAddBucketsForFullPacketCapturesResponse,
)
from .ownership_magic_pcap_collection_list_pca_ps_bucket_ownership_response import (
    OwnershipMagicPcapCollectionListPcaPsBucketOwnershipResponse as OwnershipMagicPcapCollectionListPcaPsBucketOwnershipResponse,
)
from .ownership_magic_pcap_collection_add_buckets_for_full_packet_captures_params import (
    OwnershipMagicPcapCollectionAddBucketsForFullPacketCapturesParams as OwnershipMagicPcapCollectionAddBucketsForFullPacketCapturesParams,
)
