# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from .fallback_origin import FallbackOriginResource, AsyncFallbackOriginResource
from .fallback_origin import FallbackOriginResourceWithRawResponse, AsyncFallbackOriginResourceWithRawResponse, FallbackOriginResourceWithStreamingResponse, AsyncFallbackOriginResourceWithStreamingResponse
from .custom_hostnames import CustomHostnamesResource, AsyncCustomHostnamesResource
from .custom_hostnames import CustomHostnamesResourceWithRawResponse, AsyncCustomHostnamesResourceWithRawResponse, CustomHostnamesResourceWithStreamingResponse, AsyncCustomHostnamesResourceWithStreamingResponse

__all__ = ["FallbackOriginResource", "AsyncFallbackOriginResource", "FallbackOriginResourceWithRawResponse", "AsyncFallbackOriginResourceWithRawResponse", "FallbackOriginResourceWithStreamingResponse", "AsyncFallbackOriginResourceWithStreamingResponse", "CustomHostnamesResource", "AsyncCustomHostnamesResource", "CustomHostnamesResourceWithRawResponse", "AsyncCustomHostnamesResourceWithRawResponse", "CustomHostnamesResourceWithStreamingResponse", "AsyncCustomHostnamesResourceWithStreamingResponse"]