# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .zero_rtt_get_response import ZeroRttGetResponse as ZeroRttGetResponse
from .zero_rtt_zone_settings_change_0_rtt_session_resumption_setting_response import (
    ZeroRttZoneSettingsChange0RttSessionResumptionSettingResponse as ZeroRttZoneSettingsChange0RttSessionResumptionSettingResponse,
)
from .zero_rtt_zone_settings_change_0_rtt_session_resumption_setting_params import (
    ZeroRttZoneSettingsChange0RttSessionResumptionSettingParams as ZeroRttZoneSettingsChange0RttSessionResumptionSettingParams,
)
from .advanced_ddos_get_response import AdvancedDDOSGetResponse as AdvancedDDOSGetResponse
from .always_online_update_response import AlwaysOnlineUpdateResponse as AlwaysOnlineUpdateResponse
from .always_online_get_response import AlwaysOnlineGetResponse as AlwaysOnlineGetResponse
from .always_online_update_params import AlwaysOnlineUpdateParams as AlwaysOnlineUpdateParams
from .always_use_https_update_response import AlwaysUseHTTPSUpdateResponse as AlwaysUseHTTPSUpdateResponse
from .always_use_https_get_response import AlwaysUseHTTPSGetResponse as AlwaysUseHTTPSGetResponse
from .always_use_https_update_params import AlwaysUseHTTPSUpdateParams as AlwaysUseHTTPSUpdateParams
from .automatic_https_rewrite_update_response import (
    AutomaticHTTPSRewriteUpdateResponse as AutomaticHTTPSRewriteUpdateResponse,
)
from .automatic_https_rewrite_get_response import AutomaticHTTPSRewriteGetResponse as AutomaticHTTPSRewriteGetResponse
from .automatic_https_rewrite_update_params import (
    AutomaticHTTPSRewriteUpdateParams as AutomaticHTTPSRewriteUpdateParams,
)
from .automatic_platform_optimization_update_response import (
    AutomaticPlatformOptimizationUpdateResponse as AutomaticPlatformOptimizationUpdateResponse,
)
from .automatic_platform_optimization_get_response import (
    AutomaticPlatformOptimizationGetResponse as AutomaticPlatformOptimizationGetResponse,
)
from .automatic_platform_optimization_update_params import (
    AutomaticPlatformOptimizationUpdateParams as AutomaticPlatformOptimizationUpdateParams,
)
from .brotli_update_response import BrotliUpdateResponse as BrotliUpdateResponse
from .brotli_get_response import BrotliGetResponse as BrotliGetResponse
from .brotli_update_params import BrotliUpdateParams as BrotliUpdateParams
from .browser_cache_ttl_update_response import BrowserCacheTTLUpdateResponse as BrowserCacheTTLUpdateResponse
from .browser_cache_ttl_get_response import BrowserCacheTTLGetResponse as BrowserCacheTTLGetResponse
from .browser_cache_ttl_update_params import BrowserCacheTTLUpdateParams as BrowserCacheTTLUpdateParams
from .browser_check_update_response import BrowserCheckUpdateResponse as BrowserCheckUpdateResponse
from .browser_check_get_response import BrowserCheckGetResponse as BrowserCheckGetResponse
from .browser_check_update_params import BrowserCheckUpdateParams as BrowserCheckUpdateParams
from .cache_level_update_response import CacheLevelUpdateResponse as CacheLevelUpdateResponse
from .cache_level_get_response import CacheLevelGetResponse as CacheLevelGetResponse
from .cache_level_update_params import CacheLevelUpdateParams as CacheLevelUpdateParams
from .challenge_ttl_update_response import ChallengeTTLUpdateResponse as ChallengeTTLUpdateResponse
from .challenge_ttl_get_response import ChallengeTTLGetResponse as ChallengeTTLGetResponse
from .challenge_ttl_update_params import ChallengeTTLUpdateParams as ChallengeTTLUpdateParams
from .cipher_update_response import CipherUpdateResponse as CipherUpdateResponse
from .cipher_get_response import CipherGetResponse as CipherGetResponse
from .cipher_update_params import CipherUpdateParams as CipherUpdateParams
from .development_mode_update_response import DevelopmentModeUpdateResponse as DevelopmentModeUpdateResponse
from .development_mode_get_response import DevelopmentModeGetResponse as DevelopmentModeGetResponse
from .development_mode_update_params import DevelopmentModeUpdateParams as DevelopmentModeUpdateParams
from .early_hint_update_response import EarlyHintUpdateResponse as EarlyHintUpdateResponse
from .early_hint_get_response import EarlyHintGetResponse as EarlyHintGetResponse
from .early_hint_update_params import EarlyHintUpdateParams as EarlyHintUpdateParams
from .email_obfuscation_update_response import EmailObfuscationUpdateResponse as EmailObfuscationUpdateResponse
from .email_obfuscation_get_response import EmailObfuscationGetResponse as EmailObfuscationGetResponse
from .email_obfuscation_update_params import EmailObfuscationUpdateParams as EmailObfuscationUpdateParams
from .h2_prioritization_update_response import H2PrioritizationUpdateResponse as H2PrioritizationUpdateResponse
from .h2_prioritization_get_response import H2PrioritizationGetResponse as H2PrioritizationGetResponse
from .h2_prioritization_update_params import H2PrioritizationUpdateParams as H2PrioritizationUpdateParams
from .hotlink_protection_update_response import HotlinkProtectionUpdateResponse as HotlinkProtectionUpdateResponse
from .hotlink_protection_get_response import HotlinkProtectionGetResponse as HotlinkProtectionGetResponse
from .hotlink_protection_update_params import HotlinkProtectionUpdateParams as HotlinkProtectionUpdateParams
from .http2_update_response import HTTP2UpdateResponse as HTTP2UpdateResponse
from .http2_get_response import HTTP2GetResponse as HTTP2GetResponse
from .http2_update_params import HTTP2UpdateParams as HTTP2UpdateParams
from .http3_update_response import HTTP3UpdateResponse as HTTP3UpdateResponse
from .http3_get_response import HTTP3GetResponse as HTTP3GetResponse
from .http3_update_params import HTTP3UpdateParams as HTTP3UpdateParams
from .image_resizing_update_response import ImageResizingUpdateResponse as ImageResizingUpdateResponse
from .image_resizing_get_response import ImageResizingGetResponse as ImageResizingGetResponse
from .image_resizing_update_params import ImageResizingUpdateParams as ImageResizingUpdateParams
from .ip_geolocation_update_response import IPGeolocationUpdateResponse as IPGeolocationUpdateResponse
from .ip_geolocation_get_response import IPGeolocationGetResponse as IPGeolocationGetResponse
from .ip_geolocation_update_params import IPGeolocationUpdateParams as IPGeolocationUpdateParams
from .ipv6_update_response import IPV6UpdateResponse as IPV6UpdateResponse
from .ipv6_get_response import IPV6GetResponse as IPV6GetResponse
from .ipv6_update_params import IPV6UpdateParams as IPV6UpdateParams
from .min_tls_version_update_response import MinTLSVersionUpdateResponse as MinTLSVersionUpdateResponse
from .min_tls_version_get_response import MinTLSVersionGetResponse as MinTLSVersionGetResponse
from .min_tls_version_update_params import MinTLSVersionUpdateParams as MinTLSVersionUpdateParams
from .minify_update_response import MinifyUpdateResponse as MinifyUpdateResponse
from .minify_get_response import MinifyGetResponse as MinifyGetResponse
from .minify_update_params import MinifyUpdateParams as MinifyUpdateParams
from .mirage_update_response import MirageUpdateResponse as MirageUpdateResponse
from .mirage_get_response import MirageGetResponse as MirageGetResponse
from .mirage_update_params import MirageUpdateParams as MirageUpdateParams
from .mobile_redirect_update_response import MobileRedirectUpdateResponse as MobileRedirectUpdateResponse
from .mobile_redirect_get_response import MobileRedirectGetResponse as MobileRedirectGetResponse
from .mobile_redirect_update_params import MobileRedirectUpdateParams as MobileRedirectUpdateParams
from .nel_update_response import NELUpdateResponse as NELUpdateResponse
from .nel_get_response import NELGetResponse as NELGetResponse
from .nel_update_params import NELUpdateParams as NELUpdateParams
from .opportunistic_encryption_update_response import (
    OpportunisticEncryptionUpdateResponse as OpportunisticEncryptionUpdateResponse,
)
from .opportunistic_encryption_get_response import (
    OpportunisticEncryptionGetResponse as OpportunisticEncryptionGetResponse,
)
from .opportunistic_encryption_update_params import (
    OpportunisticEncryptionUpdateParams as OpportunisticEncryptionUpdateParams,
)
from .opportunistic_onion_update_response import OpportunisticOnionUpdateResponse as OpportunisticOnionUpdateResponse
from .opportunistic_onion_get_response import OpportunisticOnionGetResponse as OpportunisticOnionGetResponse
from .opportunistic_onion_update_params import OpportunisticOnionUpdateParams as OpportunisticOnionUpdateParams
from .orange_to_orange_update_response import OrangeToOrangeUpdateResponse as OrangeToOrangeUpdateResponse
from .orange_to_orange_get_response import OrangeToOrangeGetResponse as OrangeToOrangeGetResponse
from .orange_to_orange_update_params import OrangeToOrangeUpdateParams as OrangeToOrangeUpdateParams
from .origin_error_page_pass_thru_update_response import (
    OriginErrorPagePassThruUpdateResponse as OriginErrorPagePassThruUpdateResponse,
)
from .origin_error_page_pass_thru_get_response import (
    OriginErrorPagePassThruGetResponse as OriginErrorPagePassThruGetResponse,
)
from .origin_error_page_pass_thru_update_params import (
    OriginErrorPagePassThruUpdateParams as OriginErrorPagePassThruUpdateParams,
)
from .origin_max_http_version_update_response import (
    OriginMaxHTTPVersionUpdateResponse as OriginMaxHTTPVersionUpdateResponse,
)
from .origin_max_http_version_get_response import OriginMaxHTTPVersionGetResponse as OriginMaxHTTPVersionGetResponse
from .origin_max_http_version_update_params import OriginMaxHTTPVersionUpdateParams as OriginMaxHTTPVersionUpdateParams
from .polish_update_response import PolishUpdateResponse as PolishUpdateResponse
from .polish_get_response import PolishGetResponse as PolishGetResponse
from .polish_update_params import PolishUpdateParams as PolishUpdateParams
from .prefetch_preload_update_response import PrefetchPreloadUpdateResponse as PrefetchPreloadUpdateResponse
from .prefetch_preload_get_response import PrefetchPreloadGetResponse as PrefetchPreloadGetResponse
from .prefetch_preload_update_params import PrefetchPreloadUpdateParams as PrefetchPreloadUpdateParams
from .proxy_read_timeout_update_response import ProxyReadTimeoutUpdateResponse as ProxyReadTimeoutUpdateResponse
from .proxy_read_timeout_get_response import ProxyReadTimeoutGetResponse as ProxyReadTimeoutGetResponse
from .proxy_read_timeout_update_params import ProxyReadTimeoutUpdateParams as ProxyReadTimeoutUpdateParams
from .pseudo_ipv4_update_response import PseudoIPV4UpdateResponse as PseudoIPV4UpdateResponse
from .pseudo_ipv4_get_response import PseudoIPV4GetResponse as PseudoIPV4GetResponse
from .pseudo_ipv4_update_params import PseudoIPV4UpdateParams as PseudoIPV4UpdateParams
from .response_buffering_update_response import ResponseBufferingUpdateResponse as ResponseBufferingUpdateResponse
from .response_buffering_get_response import ResponseBufferingGetResponse as ResponseBufferingGetResponse
from .response_buffering_update_params import ResponseBufferingUpdateParams as ResponseBufferingUpdateParams
from .rocket_loader_update_response import RocketLoaderUpdateResponse as RocketLoaderUpdateResponse
from .rocket_loader_get_response import RocketLoaderGetResponse as RocketLoaderGetResponse
from .rocket_loader_update_params import RocketLoaderUpdateParams as RocketLoaderUpdateParams
from .security_header_update_response import SecurityHeaderUpdateResponse as SecurityHeaderUpdateResponse
from .security_header_get_response import SecurityHeaderGetResponse as SecurityHeaderGetResponse
from .security_header_update_params import SecurityHeaderUpdateParams as SecurityHeaderUpdateParams
from .security_level_update_response import SecurityLevelUpdateResponse as SecurityLevelUpdateResponse
from .security_level_get_response import SecurityLevelGetResponse as SecurityLevelGetResponse
from .security_level_update_params import SecurityLevelUpdateParams as SecurityLevelUpdateParams
from .server_side_exclude_update_response import ServerSideExcludeUpdateResponse as ServerSideExcludeUpdateResponse
from .server_side_exclude_get_response import ServerSideExcludeGetResponse as ServerSideExcludeGetResponse
from .server_side_exclude_update_params import ServerSideExcludeUpdateParams as ServerSideExcludeUpdateParams
from .sort_query_string_for_cache_update_response import (
    SortQueryStringForCacheUpdateResponse as SortQueryStringForCacheUpdateResponse,
)
from .sort_query_string_for_cache_get_response import (
    SortQueryStringForCacheGetResponse as SortQueryStringForCacheGetResponse,
)
from .sort_query_string_for_cache_update_params import (
    SortQueryStringForCacheUpdateParams as SortQueryStringForCacheUpdateParams,
)
from .ssl_update_response import SSLUpdateResponse as SSLUpdateResponse
from .ssl_get_response import SSLGetResponse as SSLGetResponse
from .ssl_update_params import SSLUpdateParams as SSLUpdateParams
from .ssl_recommender_update_response import SSLRecommenderUpdateResponse as SSLRecommenderUpdateResponse
from .ssl_recommender_get_response import SSLRecommenderGetResponse as SSLRecommenderGetResponse
from .ssl_recommender_update_params import SSLRecommenderUpdateParams as SSLRecommenderUpdateParams
from .tls_1_3_update_response import TLS1_3UpdateResponse as TLS1_3UpdateResponse
from .tls_1_3_get_response import TLS1_3GetResponse as TLS1_3GetResponse
from .tls_1_3_update_params import TLS1_3UpdateParams as TLS1_3UpdateParams
from .tls_client_auth_update_response import TLSClientAuthUpdateResponse as TLSClientAuthUpdateResponse
from .tls_client_auth_get_response import TLSClientAuthGetResponse as TLSClientAuthGetResponse
from .tls_client_auth_update_params import TLSClientAuthUpdateParams as TLSClientAuthUpdateParams
from .true_client_ip_header_update_response import TrueClientIPHeaderUpdateResponse as TrueClientIPHeaderUpdateResponse
from .true_client_ip_header_get_response import TrueClientIPHeaderGetResponse as TrueClientIPHeaderGetResponse
from .true_client_ip_header_update_params import TrueClientIPHeaderUpdateParams as TrueClientIPHeaderUpdateParams
from .waf_update_response import WAFUpdateResponse as WAFUpdateResponse
from .waf_get_response import WAFGetResponse as WAFGetResponse
from .waf_update_params import WAFUpdateParams as WAFUpdateParams
from .webp_update_response import WebpUpdateResponse as WebpUpdateResponse
from .webp_get_response import WebpGetResponse as WebpGetResponse
from .webp_update_params import WebpUpdateParams as WebpUpdateParams
from .websocket_update_response import WebsocketUpdateResponse as WebsocketUpdateResponse
from .websocket_get_response import WebsocketGetResponse as WebsocketGetResponse
from .websocket_update_params import WebsocketUpdateParams as WebsocketUpdateParams
