# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .colo_zone_analytics_deprecated_get_analytics_by_co_locations_response import (
    ColoZoneAnalyticsDeprecatedGetAnalyticsByCoLocationsResponse as ColoZoneAnalyticsDeprecatedGetAnalyticsByCoLocationsResponse,
)
from .colo_zone_analytics_deprecated_get_analytics_by_co_locations_params import (
    ColoZoneAnalyticsDeprecatedGetAnalyticsByCoLocationsParams as ColoZoneAnalyticsDeprecatedGetAnalyticsByCoLocationsParams,
)
from .dashboard_zone_analytics_deprecated_get_dashboard_response import (
    DashboardZoneAnalyticsDeprecatedGetDashboardResponse as DashboardZoneAnalyticsDeprecatedGetDashboardResponse,
)
from .dashboard_zone_analytics_deprecated_get_dashboard_params import (
    DashboardZoneAnalyticsDeprecatedGetDashboardParams as DashboardZoneAnalyticsDeprecatedGetDashboardParams,
)
from .latency_argo_analytics_for_zone_argo_analytics_for_a_zone_response import (
    LatencyArgoAnalyticsForZoneArgoAnalyticsForAZoneResponse as LatencyArgoAnalyticsForZoneArgoAnalyticsForAZoneResponse,
)
from .latency_argo_analytics_for_zone_argo_analytics_for_a_zone_params import (
    LatencyArgoAnalyticsForZoneArgoAnalyticsForAZoneParams as LatencyArgoAnalyticsForZoneArgoAnalyticsForAZoneParams,
)
