# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .a_record import ARecord as ARecord
from .ds_record import DSRecord as DSRecord
from .mx_record import MXRecord as MXRecord
from .ns_record import NSRecord as NSRecord
from .caa_record import CAARecord as CAARecord
from .loc_record import LOCRecord as LOCRecord
from .nameserver import Nameserver as Nameserver
from .ptr_record import PTRRecord as PTRRecord
from .srv_record import SRVRecord as SRVRecord
from .txt_record import TXTRecord as TXTRecord
from .uri_record import URIRecord as URIRecord
from .aaaa_record import AAAARecord as AAAARecord
from .cert_record import CERTRecord as CERTRecord
from .dns_setting import DNSSetting as DNSSetting
from .record_tags import RecordTags as RecordTags
from .svcb_record import SVCBRecord as SVCBRecord
from .tlsa_record import TLSARecord as TLSARecord
from .cname_record import CNAMERecord as CNAMERecord
from .firewall_ips import FirewallIPs as FirewallIPs
from .https_record import HTTPSRecord as HTTPSRecord
from .naptr_record import NAPTRRecord as NAPTRRecord
from .record_param import RecordParam as RecordParam
from .sshfp_record import SSHFPRecord as SSHFPRecord
from .upstream_ips import UpstreamIPs as UpstreamIPs
from .dnskey_record import DNSKEYRecord as DNSKEYRecord
from .smimea_record import SMIMEARecord as SMIMEARecord
from .a_record_param import ARecordParam as ARecordParam
from .ds_record_param import DSRecordParam as DSRecordParam
from .mx_record_param import MXRecordParam as MXRecordParam
from .ns_record_param import NSRecordParam as NSRecordParam
from .caa_record_param import CAARecordParam as CAARecordParam
from .loc_record_param import LOCRecordParam as LOCRecordParam
from .nameserver_param import NameserverParam as NameserverParam
from .ptr_record_param import PTRRecordParam as PTRRecordParam
from .srv_record_param import SRVRecordParam as SRVRecordParam
from .txt_record_param import TXTRecordParam as TXTRecordParam
from .uri_record_param import URIRecordParam as URIRecordParam
from .aaaa_record_param import AAAARecordParam as AAAARecordParam
from .attack_mitigation import AttackMitigation as AttackMitigation
from .cert_record_param import CERTRecordParam as CERTRecordParam
from .dns_setting_param import DNSSettingParam as DNSSettingParam
from .svcb_record_param import SVCBRecordParam as SVCBRecordParam
from .tlsa_record_param import TLSARecordParam as TLSARecordParam
from .cname_record_param import CNAMERecordParam as CNAMERecordParam
from .https_record_param import HTTPSRecordParam as HTTPSRecordParam
from .naptr_record_param import NAPTRRecordParam as NAPTRRecordParam
from .record_edit_params import RecordEditParams as RecordEditParams
from .record_list_params import RecordListParams as RecordListParams
from .record_scan_params import RecordScanParams as RecordScanParams
from .sshfp_record_param import SSHFPRecordParam as SSHFPRecordParam
from .dns_analytics_query import DNSAnalyticsQuery as DNSAnalyticsQuery
from .dnskey_record_param import DNSKEYRecordParam as DNSKEYRecordParam
from .record_batch_params import RecordBatchParams as RecordBatchParams
from .record_get_response import RecordGetResponse as RecordGetResponse
from .setting_edit_params import SettingEditParams as SettingEditParams
from .smimea_record_param import SMIMEARecordParam as SMIMEARecordParam
from .firewall_edit_params import FirewallEditParams as FirewallEditParams
from .firewall_list_params import FirewallListParams as FirewallListParams
from .record_create_params import RecordCreateParams as RecordCreateParams
from .record_edit_response import RecordEditResponse as RecordEditResponse
from .record_import_params import RecordImportParams as RecordImportParams
from .record_list_response import RecordListResponse as RecordListResponse
from .record_scan_response import RecordScanResponse as RecordScanResponse
from .record_update_params import RecordUpdateParams as RecordUpdateParams
from .setting_get_response import SettingGetResponse as SettingGetResponse
from .firewall_get_response import FirewallGetResponse as FirewallGetResponse
from .record_batch_response import RecordBatchResponse as RecordBatchResponse
from .record_process_timing import RecordProcessTiming as RecordProcessTiming
from .setting_edit_response import SettingEditResponse as SettingEditResponse
from .firewall_create_params import FirewallCreateParams as FirewallCreateParams
from .firewall_edit_response import FirewallEditResponse as FirewallEditResponse
from .firewall_list_response import FirewallListResponse as FirewallListResponse
from .record_create_response import RecordCreateResponse as RecordCreateResponse
from .record_delete_response import RecordDeleteResponse as RecordDeleteResponse
from .record_export_response import RecordExportResponse as RecordExportResponse
from .record_import_response import RecordImportResponse as RecordImportResponse
from .record_update_response import RecordUpdateResponse as RecordUpdateResponse
from .attack_mitigation_param import AttackMitigationParam as AttackMitigationParam
from .firewall_create_response import FirewallCreateResponse as FirewallCreateResponse
from .firewall_delete_response import FirewallDeleteResponse as FirewallDeleteResponse
from .dns_analytics_nominal_metric import DNSAnalyticsNominalMetric as DNSAnalyticsNominalMetric
