# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .revoke_user_zero_trust_organization_revoke_all_access_tokens_for_a_user_params import (
    RevokeUserZeroTrustOrganizationRevokeAllAccessTokensForAUserParams as RevokeUserZeroTrustOrganizationRevokeAllAccessTokensForAUserParams,
)
from .revoke_user_zero_trust_organization_revoke_all_access_tokens_for_a_user_response import (
    RevokeUserZeroTrustOrganizationRevokeAllAccessTokensForAUserResponse as RevokeUserZeroTrustOrganizationRevokeAllAccessTokensForAUserResponse,
)
