# File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

from __future__ import annotations

from .zone_authenticated_origin_pull import ZoneAuthenticatedOriginPull as ZoneAuthenticatedOriginPull
from .origin_tls_client_auth_create_params import OriginTLSClientAuthCreateParams as OriginTLSClientAuthCreateParams
from .authenticated_origin_pull import AuthenticatedOriginPull as AuthenticatedOriginPull
from .hostname_update_response import HostnameUpdateResponse as HostnameUpdateResponse
from .hostname_update_params import HostnameUpdateParams as HostnameUpdateParams
from .setting_update_response import SettingUpdateResponse as SettingUpdateResponse
from .setting_get_response import SettingGetResponse as SettingGetResponse
from .setting_update_params import SettingUpdateParams as SettingUpdateParams
