# File generated from our OpenAPI spec by Stainless.

from __future__ import annotations

from .intel_permissions_update import IntelPermissionsUpdate as IntelPermissionsUpdate
from .permission_create_params import PermissionCreateParams as PermissionCreateParams
from .permission_delete_params import PermissionDeleteParams as PermissionDeleteParams
from .permission_list_response import PermissionListResponse as PermissionListResponse
from .intel_permission_list_item import IntelPermissionListItem as IntelPermissionListItem
